services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: paymentgateway-sql
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql  # ⚡ این خط باعث میشه دیتابیس حفظ بشه
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourPassword123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paymentgateway-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PaymentGatewayDockerDb;User Id=sa;Password=YourPassword123;TrustServerCertificate=True"
    depends_on:
      - sqlserver
  
    networks:
      - paymentgateway-net
    restart: unless-stopped

networks:
  paymentgateway-net:
    driver: bridge

volumes:
  sqlserver-data:   # ⚡ volume تعریف شده برای حفظ دیتابیس
