apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: wait-for-sql
        image: mcr.microsoft.com/mssql-tools
        command:
          - /bin/bash
          - -c
          - |
            echo "Waiting for SQL Server..."
            until sqlcmd -S sqlserver-service,1433 -U sa -P "YourPassword123" -Q "SELECT 1" > /dev/null 2>&1; do
              sleep 5
            done
            echo "SQL Server is ready"
      containers:
      - name: paymentgateway-api
        image: paymentgatewayapi-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver-service,1433;Database=PaymentGatewayDockerDb;User Id=sa;Password=YourPassword123;TrustServerCertificate=True"
